name: Deploy to Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_DEPLOY_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ls -l ~/.ssh
          cat ~/.ssh/github_deploy_key | head -5
          echo "PI_HOST is: ${{ secrets.PI_HOST }}"
          ssh-keyscan ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
          
      - name: Test SSH to Pi
        run: |
          ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} 'hostname'
          
      - name: Deploy to Pi
        run: |
          ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} 'cd incent-A1 && git pull && systemctl restart incent-a1.service'
